# -*- coding: utf-8 -*-
"""Lemang_RailFence.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JJEVMwMABCQvYeo_WEwUsV_cYvq0emUI
"""

def wave_rail_fence_encrypt(plaintext, rails):
    "=== Verified Rail Fence Cipher ==="
    if rails < 2:
        raise ValueError("Must have at least 2 rails")

    rail_lines = [[] for _ in range(rails)]
    current_rail = 0
    direction = 1  # 1 = down, -1 = up

    for char in plaintext:
        if char.isalpha():  # Only process letters
            rail_lines[current_rail].append(char.upper())
            current_rail += direction
            if current_rail in (0, rails - 1):
                direction *= -1

    return ''.join([''.join(rail) for rail in rail_lines])

def main():
    print("=== Rail Fence Cipher ===")

    plaintext = input("Enter message: ")
    rails = int(input("Number of rails (>=2): "))

    try:
        encrypted = wave_rail_fence_encrypt(plaintext, rails)
        print(f"\nEncrypted: {encrypted}")
    except ValueError as e:
        print(f"Error: {e}")

if __name__ == "__main__":
    main()